FROM python:3.11.12-slim-bookworm

# 安裝必要套件
RUN apt-get update && \
    apt-get upgrade -y && \ 
    apt-get install -y --no-install-recommends \
    openssh-server \
    vim \
    git \
    net-tools \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 建立 Flask 資料夾
RUN mkdir /app
WORKDIR /app

# 複製需求套件並安裝
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt || cat requirements.txt

# SSH 設定
RUN mkdir /var/run/sshd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# 加入環境變數用於密碼設置（預設為 ncume ）
ENV ROOTPWD=ncume
ENV FLASK_APP=app.py

# 對外開放 Flask 與 SSH port
EXPOSE 5000 22

# 建立啟動 script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 啟動時才設定 root 密碼並啟動 SSH + Flask
# DOCKER建議：最好以JSON格式處理指令，而非SHELL指令
CMD ["/entrypoint.sh"]
